// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jmrflora/bazarTudao/ent/cliente"
	"github.com/jmrflora/bazarTudao/ent/ordem"
	"github.com/jmrflora/bazarTudao/ent/predicate"
)

// ClienteQuery is the builder for querying Cliente entities.
type ClienteQuery struct {
	config
	ctx        *QueryContext
	order      []cliente.OrderOption
	inters     []Interceptor
	predicates []predicate.Cliente
	withOrdens *OrdemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ClienteQuery builder.
func (cq *ClienteQuery) Where(ps ...predicate.Cliente) *ClienteQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *ClienteQuery) Limit(limit int) *ClienteQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *ClienteQuery) Offset(offset int) *ClienteQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *ClienteQuery) Unique(unique bool) *ClienteQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *ClienteQuery) Order(o ...cliente.OrderOption) *ClienteQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryOrdens chains the current query on the "ordens" edge.
func (cq *ClienteQuery) QueryOrdens() *OrdemQuery {
	query := (&OrdemClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cliente.Table, cliente.FieldID, selector),
			sqlgraph.To(ordem.Table, ordem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, cliente.OrdensTable, cliente.OrdensColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Cliente entity from the query.
// Returns a *NotFoundError when no Cliente was found.
func (cq *ClienteQuery) First(ctx context.Context) (*Cliente, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cliente.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *ClienteQuery) FirstX(ctx context.Context) *Cliente {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Cliente ID from the query.
// Returns a *NotFoundError when no Cliente ID was found.
func (cq *ClienteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cliente.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *ClienteQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Cliente entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Cliente entity is found.
// Returns a *NotFoundError when no Cliente entities are found.
func (cq *ClienteQuery) Only(ctx context.Context) (*Cliente, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cliente.Label}
	default:
		return nil, &NotSingularError{cliente.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *ClienteQuery) OnlyX(ctx context.Context) *Cliente {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Cliente ID in the query.
// Returns a *NotSingularError when more than one Cliente ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *ClienteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cliente.Label}
	default:
		err = &NotSingularError{cliente.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *ClienteQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Clientes.
func (cq *ClienteQuery) All(ctx context.Context) ([]*Cliente, error) {
	ctx = setContextOp(ctx, cq.ctx, "All")
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Cliente, *ClienteQuery]()
	return withInterceptors[[]*Cliente](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *ClienteQuery) AllX(ctx context.Context) []*Cliente {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Cliente IDs.
func (cq *ClienteQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, "IDs")
	if err = cq.Select(cliente.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *ClienteQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *ClienteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, "Count")
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*ClienteQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *ClienteQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *ClienteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, "Exist")
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *ClienteQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ClienteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *ClienteQuery) Clone() *ClienteQuery {
	if cq == nil {
		return nil
	}
	return &ClienteQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]cliente.OrderOption{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.Cliente{}, cq.predicates...),
		withOrdens: cq.withOrdens.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithOrdens tells the query-builder to eager-load the nodes that are connected to
// the "ordens" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ClienteQuery) WithOrdens(opts ...func(*OrdemQuery)) *ClienteQuery {
	query := (&OrdemClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withOrdens = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Email string `json:"email,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Cliente.Query().
//		GroupBy(cliente.FieldEmail).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *ClienteQuery) GroupBy(field string, fields ...string) *ClienteGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ClienteGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = cliente.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Email string `json:"email,omitempty"`
//	}
//
//	client.Cliente.Query().
//		Select(cliente.FieldEmail).
//		Scan(ctx, &v)
func (cq *ClienteQuery) Select(fields ...string) *ClienteSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &ClienteSelect{ClienteQuery: cq}
	sbuild.label = cliente.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ClienteSelect configured with the given aggregations.
func (cq *ClienteQuery) Aggregate(fns ...AggregateFunc) *ClienteSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *ClienteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !cliente.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *ClienteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Cliente, error) {
	var (
		nodes       = []*Cliente{}
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withOrdens != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Cliente).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Cliente{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withOrdens; query != nil {
		if err := cq.loadOrdens(ctx, query, nodes,
			func(n *Cliente) { n.Edges.Ordens = []*Ordem{} },
			func(n *Cliente, e *Ordem) { n.Edges.Ordens = append(n.Edges.Ordens, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *ClienteQuery) loadOrdens(ctx context.Context, query *OrdemQuery, nodes []*Cliente, init func(*Cliente), assign func(*Cliente, *Ordem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Cliente)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Ordem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(cliente.OrdensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.cliente_ordens
		if fk == nil {
			return fmt.Errorf(`foreign-key "cliente_ordens" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "cliente_ordens" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *ClienteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *ClienteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cliente.Table, cliente.Columns, sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cliente.FieldID)
		for i := range fields {
			if fields[i] != cliente.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *ClienteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(cliente.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = cliente.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClienteGroupBy is the group-by builder for Cliente entities.
type ClienteGroupBy struct {
	selector
	build *ClienteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *ClienteGroupBy) Aggregate(fns ...AggregateFunc) *ClienteGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *ClienteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, "GroupBy")
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClienteQuery, *ClienteGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *ClienteGroupBy) sqlScan(ctx context.Context, root *ClienteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ClienteSelect is the builder for selecting fields of Cliente entities.
type ClienteSelect struct {
	*ClienteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *ClienteSelect) Aggregate(fns ...AggregateFunc) *ClienteSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *ClienteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, "Select")
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClienteQuery, *ClienteSelect](ctx, cs.ClienteQuery, cs, cs.inters, v)
}

func (cs *ClienteSelect) sqlScan(ctx context.Context, root *ClienteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
