// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jmrflora/bazarTudao/ent/cliente"
	"github.com/jmrflora/bazarTudao/ent/ordem"
)

// ClienteCreate is the builder for creating a Cliente entity.
type ClienteCreate struct {
	config
	mutation *ClienteMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (cc *ClienteCreate) SetEmail(s string) *ClienteCreate {
	cc.mutation.SetEmail(s)
	return cc
}

// SetNome sets the "nome" field.
func (cc *ClienteCreate) SetNome(s string) *ClienteCreate {
	cc.mutation.SetNome(s)
	return cc
}

// SetCpf sets the "cpf" field.
func (cc *ClienteCreate) SetCpf(s string) *ClienteCreate {
	cc.mutation.SetCpf(s)
	return cc
}

// SetTelefone sets the "telefone" field.
func (cc *ClienteCreate) SetTelefone(s string) *ClienteCreate {
	cc.mutation.SetTelefone(s)
	return cc
}

// SetEnderecoEntrega sets the "endereco_entrega" field.
func (cc *ClienteCreate) SetEnderecoEntrega(s string) *ClienteCreate {
	cc.mutation.SetEnderecoEntrega(s)
	return cc
}

// AddOrdenIDs adds the "ordens" edge to the Ordem entity by IDs.
func (cc *ClienteCreate) AddOrdenIDs(ids ...int) *ClienteCreate {
	cc.mutation.AddOrdenIDs(ids...)
	return cc
}

// AddOrdens adds the "ordens" edges to the Ordem entity.
func (cc *ClienteCreate) AddOrdens(o ...*Ordem) *ClienteCreate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return cc.AddOrdenIDs(ids...)
}

// Mutation returns the ClienteMutation object of the builder.
func (cc *ClienteCreate) Mutation() *ClienteMutation {
	return cc.mutation
}

// Save creates the Cliente in the database.
func (cc *ClienteCreate) Save(ctx context.Context) (*Cliente, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ClienteCreate) SaveX(ctx context.Context) *Cliente {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ClienteCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ClienteCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ClienteCreate) check() error {
	if _, ok := cc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Cliente.email"`)}
	}
	if _, ok := cc.mutation.Nome(); !ok {
		return &ValidationError{Name: "nome", err: errors.New(`ent: missing required field "Cliente.nome"`)}
	}
	if _, ok := cc.mutation.Cpf(); !ok {
		return &ValidationError{Name: "cpf", err: errors.New(`ent: missing required field "Cliente.cpf"`)}
	}
	if _, ok := cc.mutation.Telefone(); !ok {
		return &ValidationError{Name: "telefone", err: errors.New(`ent: missing required field "Cliente.telefone"`)}
	}
	if _, ok := cc.mutation.EnderecoEntrega(); !ok {
		return &ValidationError{Name: "endereco_entrega", err: errors.New(`ent: missing required field "Cliente.endereco_entrega"`)}
	}
	return nil
}

func (cc *ClienteCreate) sqlSave(ctx context.Context) (*Cliente, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ClienteCreate) createSpec() (*Cliente, *sqlgraph.CreateSpec) {
	var (
		_node = &Cliente{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(cliente.Table, sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.Email(); ok {
		_spec.SetField(cliente.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := cc.mutation.Nome(); ok {
		_spec.SetField(cliente.FieldNome, field.TypeString, value)
		_node.Nome = value
	}
	if value, ok := cc.mutation.Cpf(); ok {
		_spec.SetField(cliente.FieldCpf, field.TypeString, value)
		_node.Cpf = value
	}
	if value, ok := cc.mutation.Telefone(); ok {
		_spec.SetField(cliente.FieldTelefone, field.TypeString, value)
		_node.Telefone = value
	}
	if value, ok := cc.mutation.EnderecoEntrega(); ok {
		_spec.SetField(cliente.FieldEnderecoEntrega, field.TypeString, value)
		_node.EnderecoEntrega = value
	}
	if nodes := cc.mutation.OrdensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cliente.OrdensTable,
			Columns: []string{cliente.OrdensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClienteCreateBulk is the builder for creating many Cliente entities in bulk.
type ClienteCreateBulk struct {
	config
	err      error
	builders []*ClienteCreate
}

// Save creates the Cliente entities in the database.
func (ccb *ClienteCreateBulk) Save(ctx context.Context) ([]*Cliente, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Cliente, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClienteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ClienteCreateBulk) SaveX(ctx context.Context) []*Cliente {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ClienteCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ClienteCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
