// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jmrflora/bazarTudao/ent/envio"
	"github.com/jmrflora/bazarTudao/ent/itemordem"
)

// EnvioCreate is the builder for creating a Envio entity.
type EnvioCreate struct {
	config
	mutation *EnvioMutation
	hooks    []Hook
}

// SetData sets the "data" field.
func (ec *EnvioCreate) SetData(t time.Time) *EnvioCreate {
	ec.mutation.SetData(t)
	return ec
}

// SetNillableData sets the "data" field if the given value is not nil.
func (ec *EnvioCreate) SetNillableData(t *time.Time) *EnvioCreate {
	if t != nil {
		ec.SetData(*t)
	}
	return ec
}

// AddItenIDs adds the "itens" edge to the ItemOrdem entity by IDs.
func (ec *EnvioCreate) AddItenIDs(ids ...int) *EnvioCreate {
	ec.mutation.AddItenIDs(ids...)
	return ec
}

// AddItens adds the "itens" edges to the ItemOrdem entity.
func (ec *EnvioCreate) AddItens(i ...*ItemOrdem) *EnvioCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return ec.AddItenIDs(ids...)
}

// Mutation returns the EnvioMutation object of the builder.
func (ec *EnvioCreate) Mutation() *EnvioMutation {
	return ec.mutation
}

// Save creates the Envio in the database.
func (ec *EnvioCreate) Save(ctx context.Context) (*Envio, error) {
	ec.defaults()
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EnvioCreate) SaveX(ctx context.Context) *Envio {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EnvioCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EnvioCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *EnvioCreate) defaults() {
	if _, ok := ec.mutation.Data(); !ok {
		v := envio.DefaultData()
		ec.mutation.SetData(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EnvioCreate) check() error {
	if _, ok := ec.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "Envio.data"`)}
	}
	return nil
}

func (ec *EnvioCreate) sqlSave(ctx context.Context) (*Envio, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *EnvioCreate) createSpec() (*Envio, *sqlgraph.CreateSpec) {
	var (
		_node = &Envio{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(envio.Table, sqlgraph.NewFieldSpec(envio.FieldID, field.TypeInt))
	)
	if value, ok := ec.mutation.Data(); ok {
		_spec.SetField(envio.FieldData, field.TypeTime, value)
		_node.Data = value
	}
	if nodes := ec.mutation.ItensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   envio.ItensTable,
			Columns: []string{envio.ItensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itemordem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnvioCreateBulk is the builder for creating many Envio entities in bulk.
type EnvioCreateBulk struct {
	config
	err      error
	builders []*EnvioCreate
}

// Save creates the Envio entities in the database.
func (ecb *EnvioCreateBulk) Save(ctx context.Context) ([]*Envio, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Envio, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnvioMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EnvioCreateBulk) SaveX(ctx context.Context) []*Envio {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EnvioCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EnvioCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
