// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jmrflora/bazarTudao/ent/cliente"
	"github.com/jmrflora/bazarTudao/ent/itemordem"
	"github.com/jmrflora/bazarTudao/ent/ordem"
	"github.com/jmrflora/bazarTudao/ent/predicate"
	"github.com/jmrflora/bazarTudao/ent/produto"
)

// OrdemQuery is the builder for querying Ordem entities.
type OrdemQuery struct {
	config
	ctx          *QueryContext
	order        []ordem.OrderOption
	inters       []Interceptor
	predicates   []predicate.Ordem
	withProdutos *ProdutoQuery
	withClientes *ClienteQuery
	withItems    *ItemOrdemQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrdemQuery builder.
func (oq *OrdemQuery) Where(ps ...predicate.Ordem) *OrdemQuery {
	oq.predicates = append(oq.predicates, ps...)
	return oq
}

// Limit the number of records to be returned by this query.
func (oq *OrdemQuery) Limit(limit int) *OrdemQuery {
	oq.ctx.Limit = &limit
	return oq
}

// Offset to start from.
func (oq *OrdemQuery) Offset(offset int) *OrdemQuery {
	oq.ctx.Offset = &offset
	return oq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oq *OrdemQuery) Unique(unique bool) *OrdemQuery {
	oq.ctx.Unique = &unique
	return oq
}

// Order specifies how the records should be ordered.
func (oq *OrdemQuery) Order(o ...ordem.OrderOption) *OrdemQuery {
	oq.order = append(oq.order, o...)
	return oq
}

// QueryProdutos chains the current query on the "produtos" edge.
func (oq *OrdemQuery) QueryProdutos() *ProdutoQuery {
	query := (&ProdutoClient{config: oq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ordem.Table, ordem.FieldID, selector),
			sqlgraph.To(produto.Table, produto.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ordem.ProdutosTable, ordem.ProdutosPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(oq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClientes chains the current query on the "clientes" edge.
func (oq *OrdemQuery) QueryClientes() *ClienteQuery {
	query := (&ClienteClient{config: oq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ordem.Table, ordem.FieldID, selector),
			sqlgraph.To(cliente.Table, cliente.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ordem.ClientesTable, ordem.ClientesColumn),
		)
		fromU = sqlgraph.SetNeighbors(oq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryItems chains the current query on the "items" edge.
func (oq *OrdemQuery) QueryItems() *ItemOrdemQuery {
	query := (&ItemOrdemClient{config: oq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ordem.Table, ordem.FieldID, selector),
			sqlgraph.To(itemordem.Table, itemordem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ordem.ItemsTable, ordem.ItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(oq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Ordem entity from the query.
// Returns a *NotFoundError when no Ordem was found.
func (oq *OrdemQuery) First(ctx context.Context) (*Ordem, error) {
	nodes, err := oq.Limit(1).All(setContextOp(ctx, oq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ordem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oq *OrdemQuery) FirstX(ctx context.Context) *Ordem {
	node, err := oq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Ordem ID from the query.
// Returns a *NotFoundError when no Ordem ID was found.
func (oq *OrdemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oq.Limit(1).IDs(setContextOp(ctx, oq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ordem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oq *OrdemQuery) FirstIDX(ctx context.Context) int {
	id, err := oq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Ordem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Ordem entity is found.
// Returns a *NotFoundError when no Ordem entities are found.
func (oq *OrdemQuery) Only(ctx context.Context) (*Ordem, error) {
	nodes, err := oq.Limit(2).All(setContextOp(ctx, oq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ordem.Label}
	default:
		return nil, &NotSingularError{ordem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oq *OrdemQuery) OnlyX(ctx context.Context) *Ordem {
	node, err := oq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Ordem ID in the query.
// Returns a *NotSingularError when more than one Ordem ID is found.
// Returns a *NotFoundError when no entities are found.
func (oq *OrdemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oq.Limit(2).IDs(setContextOp(ctx, oq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ordem.Label}
	default:
		err = &NotSingularError{ordem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oq *OrdemQuery) OnlyIDX(ctx context.Context) int {
	id, err := oq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Ordems.
func (oq *OrdemQuery) All(ctx context.Context) ([]*Ordem, error) {
	ctx = setContextOp(ctx, oq.ctx, "All")
	if err := oq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Ordem, *OrdemQuery]()
	return withInterceptors[[]*Ordem](ctx, oq, qr, oq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oq *OrdemQuery) AllX(ctx context.Context) []*Ordem {
	nodes, err := oq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Ordem IDs.
func (oq *OrdemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oq.ctx.Unique == nil && oq.path != nil {
		oq.Unique(true)
	}
	ctx = setContextOp(ctx, oq.ctx, "IDs")
	if err = oq.Select(ordem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oq *OrdemQuery) IDsX(ctx context.Context) []int {
	ids, err := oq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oq *OrdemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oq.ctx, "Count")
	if err := oq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oq, querierCount[*OrdemQuery](), oq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oq *OrdemQuery) CountX(ctx context.Context) int {
	count, err := oq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oq *OrdemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oq.ctx, "Exist")
	switch _, err := oq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oq *OrdemQuery) ExistX(ctx context.Context) bool {
	exist, err := oq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrdemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oq *OrdemQuery) Clone() *OrdemQuery {
	if oq == nil {
		return nil
	}
	return &OrdemQuery{
		config:       oq.config,
		ctx:          oq.ctx.Clone(),
		order:        append([]ordem.OrderOption{}, oq.order...),
		inters:       append([]Interceptor{}, oq.inters...),
		predicates:   append([]predicate.Ordem{}, oq.predicates...),
		withProdutos: oq.withProdutos.Clone(),
		withClientes: oq.withClientes.Clone(),
		withItems:    oq.withItems.Clone(),
		// clone intermediate query.
		sql:  oq.sql.Clone(),
		path: oq.path,
	}
}

// WithProdutos tells the query-builder to eager-load the nodes that are connected to
// the "produtos" edge. The optional arguments are used to configure the query builder of the edge.
func (oq *OrdemQuery) WithProdutos(opts ...func(*ProdutoQuery)) *OrdemQuery {
	query := (&ProdutoClient{config: oq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oq.withProdutos = query
	return oq
}

// WithClientes tells the query-builder to eager-load the nodes that are connected to
// the "clientes" edge. The optional arguments are used to configure the query builder of the edge.
func (oq *OrdemQuery) WithClientes(opts ...func(*ClienteQuery)) *OrdemQuery {
	query := (&ClienteClient{config: oq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oq.withClientes = query
	return oq
}

// WithItems tells the query-builder to eager-load the nodes that are connected to
// the "items" edge. The optional arguments are used to configure the query builder of the edge.
func (oq *OrdemQuery) WithItems(opts ...func(*ItemOrdemQuery)) *OrdemQuery {
	query := (&ItemOrdemClient{config: oq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oq.withItems = query
	return oq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DataOrdem time.Time `json:"data_ordem,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Ordem.Query().
//		GroupBy(ordem.FieldDataOrdem).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oq *OrdemQuery) GroupBy(field string, fields ...string) *OrdemGroupBy {
	oq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrdemGroupBy{build: oq}
	grbuild.flds = &oq.ctx.Fields
	grbuild.label = ordem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DataOrdem time.Time `json:"data_ordem,omitempty"`
//	}
//
//	client.Ordem.Query().
//		Select(ordem.FieldDataOrdem).
//		Scan(ctx, &v)
func (oq *OrdemQuery) Select(fields ...string) *OrdemSelect {
	oq.ctx.Fields = append(oq.ctx.Fields, fields...)
	sbuild := &OrdemSelect{OrdemQuery: oq}
	sbuild.label = ordem.Label
	sbuild.flds, sbuild.scan = &oq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrdemSelect configured with the given aggregations.
func (oq *OrdemQuery) Aggregate(fns ...AggregateFunc) *OrdemSelect {
	return oq.Select().Aggregate(fns...)
}

func (oq *OrdemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oq); err != nil {
				return err
			}
		}
	}
	for _, f := range oq.ctx.Fields {
		if !ordem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oq.path != nil {
		prev, err := oq.path(ctx)
		if err != nil {
			return err
		}
		oq.sql = prev
	}
	return nil
}

func (oq *OrdemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Ordem, error) {
	var (
		nodes       = []*Ordem{}
		withFKs     = oq.withFKs
		_spec       = oq.querySpec()
		loadedTypes = [3]bool{
			oq.withProdutos != nil,
			oq.withClientes != nil,
			oq.withItems != nil,
		}
	)
	if oq.withClientes != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, ordem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Ordem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Ordem{config: oq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oq.withProdutos; query != nil {
		if err := oq.loadProdutos(ctx, query, nodes,
			func(n *Ordem) { n.Edges.Produtos = []*Produto{} },
			func(n *Ordem, e *Produto) { n.Edges.Produtos = append(n.Edges.Produtos, e) }); err != nil {
			return nil, err
		}
	}
	if query := oq.withClientes; query != nil {
		if err := oq.loadClientes(ctx, query, nodes, nil,
			func(n *Ordem, e *Cliente) { n.Edges.Clientes = e }); err != nil {
			return nil, err
		}
	}
	if query := oq.withItems; query != nil {
		if err := oq.loadItems(ctx, query, nodes,
			func(n *Ordem) { n.Edges.Items = []*ItemOrdem{} },
			func(n *Ordem, e *ItemOrdem) { n.Edges.Items = append(n.Edges.Items, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oq *OrdemQuery) loadProdutos(ctx context.Context, query *ProdutoQuery, nodes []*Ordem, init func(*Ordem), assign func(*Ordem, *Produto)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Ordem)
	nids := make(map[int]map[*Ordem]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(ordem.ProdutosTable)
		s.Join(joinT).On(s.C(produto.FieldID), joinT.C(ordem.ProdutosPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(ordem.ProdutosPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(ordem.ProdutosPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Ordem]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Produto](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "produtos" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (oq *OrdemQuery) loadClientes(ctx context.Context, query *ClienteQuery, nodes []*Ordem, init func(*Ordem), assign func(*Ordem, *Cliente)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Ordem)
	for i := range nodes {
		if nodes[i].cliente_ordens == nil {
			continue
		}
		fk := *nodes[i].cliente_ordens
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cliente.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cliente_ordens" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (oq *OrdemQuery) loadItems(ctx context.Context, query *ItemOrdemQuery, nodes []*Ordem, init func(*Ordem), assign func(*Ordem, *ItemOrdem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Ordem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(itemordem.FieldOrdemID)
	}
	query.Where(predicate.ItemOrdem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ordem.ItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrdemID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ordem_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (oq *OrdemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oq.querySpec()
	_spec.Node.Columns = oq.ctx.Fields
	if len(oq.ctx.Fields) > 0 {
		_spec.Unique = oq.ctx.Unique != nil && *oq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oq.driver, _spec)
}

func (oq *OrdemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ordem.Table, ordem.Columns, sqlgraph.NewFieldSpec(ordem.FieldID, field.TypeInt))
	_spec.From = oq.sql
	if unique := oq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oq.path != nil {
		_spec.Unique = true
	}
	if fields := oq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ordem.FieldID)
		for i := range fields {
			if fields[i] != ordem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oq *OrdemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oq.driver.Dialect())
	t1 := builder.Table(ordem.Table)
	columns := oq.ctx.Fields
	if len(columns) == 0 {
		columns = ordem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oq.sql != nil {
		selector = oq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oq.ctx.Unique != nil && *oq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oq.predicates {
		p(selector)
	}
	for _, p := range oq.order {
		p(selector)
	}
	if offset := oq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrdemGroupBy is the group-by builder for Ordem entities.
type OrdemGroupBy struct {
	selector
	build *OrdemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ogb *OrdemGroupBy) Aggregate(fns ...AggregateFunc) *OrdemGroupBy {
	ogb.fns = append(ogb.fns, fns...)
	return ogb
}

// Scan applies the selector query and scans the result into the given value.
func (ogb *OrdemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ogb.build.ctx, "GroupBy")
	if err := ogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrdemQuery, *OrdemGroupBy](ctx, ogb.build, ogb, ogb.build.inters, v)
}

func (ogb *OrdemGroupBy) sqlScan(ctx context.Context, root *OrdemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ogb.fns))
	for _, fn := range ogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ogb.flds)+len(ogb.fns))
		for _, f := range *ogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrdemSelect is the builder for selecting fields of Ordem entities.
type OrdemSelect struct {
	*OrdemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (os *OrdemSelect) Aggregate(fns ...AggregateFunc) *OrdemSelect {
	os.fns = append(os.fns, fns...)
	return os
}

// Scan applies the selector query and scans the result into the given value.
func (os *OrdemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, os.ctx, "Select")
	if err := os.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrdemQuery, *OrdemSelect](ctx, os.OrdemQuery, os, os.inters, v)
}

func (os *OrdemSelect) sqlScan(ctx context.Context, root *OrdemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(os.fns))
	for _, fn := range os.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*os.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := os.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
