// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jmrflora/bazarTudao/ent/cliente"
	"github.com/jmrflora/bazarTudao/ent/itemordem"
	"github.com/jmrflora/bazarTudao/ent/ordem"
	"github.com/jmrflora/bazarTudao/ent/produto"
)

// OrdemCreate is the builder for creating a Ordem entity.
type OrdemCreate struct {
	config
	mutation *OrdemMutation
	hooks    []Hook
}

// SetDataOrdem sets the "data_ordem" field.
func (oc *OrdemCreate) SetDataOrdem(t time.Time) *OrdemCreate {
	oc.mutation.SetDataOrdem(t)
	return oc
}

// AddProdutoIDs adds the "produtos" edge to the Produto entity by IDs.
func (oc *OrdemCreate) AddProdutoIDs(ids ...int) *OrdemCreate {
	oc.mutation.AddProdutoIDs(ids...)
	return oc
}

// AddProdutos adds the "produtos" edges to the Produto entity.
func (oc *OrdemCreate) AddProdutos(p ...*Produto) *OrdemCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return oc.AddProdutoIDs(ids...)
}

// SetClientesID sets the "clientes" edge to the Cliente entity by ID.
func (oc *OrdemCreate) SetClientesID(id int) *OrdemCreate {
	oc.mutation.SetClientesID(id)
	return oc
}

// SetNillableClientesID sets the "clientes" edge to the Cliente entity by ID if the given value is not nil.
func (oc *OrdemCreate) SetNillableClientesID(id *int) *OrdemCreate {
	if id != nil {
		oc = oc.SetClientesID(*id)
	}
	return oc
}

// SetClientes sets the "clientes" edge to the Cliente entity.
func (oc *OrdemCreate) SetClientes(c *Cliente) *OrdemCreate {
	return oc.SetClientesID(c.ID)
}

// AddItemIDs adds the "items" edge to the ItemOrdem entity by IDs.
func (oc *OrdemCreate) AddItemIDs(ids ...int) *OrdemCreate {
	oc.mutation.AddItemIDs(ids...)
	return oc
}

// AddItems adds the "items" edges to the ItemOrdem entity.
func (oc *OrdemCreate) AddItems(i ...*ItemOrdem) *OrdemCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return oc.AddItemIDs(ids...)
}

// Mutation returns the OrdemMutation object of the builder.
func (oc *OrdemCreate) Mutation() *OrdemMutation {
	return oc.mutation
}

// Save creates the Ordem in the database.
func (oc *OrdemCreate) Save(ctx context.Context) (*Ordem, error) {
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OrdemCreate) SaveX(ctx context.Context) *Ordem {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OrdemCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OrdemCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OrdemCreate) check() error {
	if _, ok := oc.mutation.DataOrdem(); !ok {
		return &ValidationError{Name: "data_ordem", err: errors.New(`ent: missing required field "Ordem.data_ordem"`)}
	}
	return nil
}

func (oc *OrdemCreate) sqlSave(ctx context.Context) (*Ordem, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OrdemCreate) createSpec() (*Ordem, *sqlgraph.CreateSpec) {
	var (
		_node = &Ordem{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(ordem.Table, sqlgraph.NewFieldSpec(ordem.FieldID, field.TypeInt))
	)
	if value, ok := oc.mutation.DataOrdem(); ok {
		_spec.SetField(ordem.FieldDataOrdem, field.TypeTime, value)
		_node.DataOrdem = value
	}
	if nodes := oc.mutation.ProdutosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ordem.ProdutosTable,
			Columns: ordem.ProdutosPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(produto.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := oc.mutation.ClientesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ordem.ClientesTable,
			Columns: []string{ordem.ClientesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliente.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.cliente_ordens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := oc.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   ordem.ItemsTable,
			Columns: []string{ordem.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itemordem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrdemCreateBulk is the builder for creating many Ordem entities in bulk.
type OrdemCreateBulk struct {
	config
	err      error
	builders []*OrdemCreate
}

// Save creates the Ordem entities in the database.
func (ocb *OrdemCreateBulk) Save(ctx context.Context) ([]*Ordem, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Ordem, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrdemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OrdemCreateBulk) SaveX(ctx context.Context) []*Ordem {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OrdemCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OrdemCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
