// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jmrflora/bazarTudao/ent/itemordem"
	"github.com/jmrflora/bazarTudao/ent/ordem"
	"github.com/jmrflora/bazarTudao/ent/predicate"
	"github.com/jmrflora/bazarTudao/ent/produto"
)

// ProdutoQuery is the builder for querying Produto entities.
type ProdutoQuery struct {
	config
	ctx        *QueryContext
	order      []produto.OrderOption
	inters     []Interceptor
	predicates []predicate.Produto
	withOrdens *OrdemQuery
	withItens  *ItemOrdemQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProdutoQuery builder.
func (pq *ProdutoQuery) Where(ps ...predicate.Produto) *ProdutoQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *ProdutoQuery) Limit(limit int) *ProdutoQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *ProdutoQuery) Offset(offset int) *ProdutoQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *ProdutoQuery) Unique(unique bool) *ProdutoQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *ProdutoQuery) Order(o ...produto.OrderOption) *ProdutoQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryOrdens chains the current query on the "ordens" edge.
func (pq *ProdutoQuery) QueryOrdens() *OrdemQuery {
	query := (&OrdemClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(produto.Table, produto.FieldID, selector),
			sqlgraph.To(ordem.Table, ordem.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, produto.OrdensTable, produto.OrdensPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryItens chains the current query on the "itens" edge.
func (pq *ProdutoQuery) QueryItens() *ItemOrdemQuery {
	query := (&ItemOrdemClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(produto.Table, produto.FieldID, selector),
			sqlgraph.To(itemordem.Table, itemordem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, produto.ItensTable, produto.ItensColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Produto entity from the query.
// Returns a *NotFoundError when no Produto was found.
func (pq *ProdutoQuery) First(ctx context.Context) (*Produto, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{produto.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *ProdutoQuery) FirstX(ctx context.Context) *Produto {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Produto ID from the query.
// Returns a *NotFoundError when no Produto ID was found.
func (pq *ProdutoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{produto.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *ProdutoQuery) FirstIDX(ctx context.Context) int {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Produto entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Produto entity is found.
// Returns a *NotFoundError when no Produto entities are found.
func (pq *ProdutoQuery) Only(ctx context.Context) (*Produto, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{produto.Label}
	default:
		return nil, &NotSingularError{produto.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *ProdutoQuery) OnlyX(ctx context.Context) *Produto {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Produto ID in the query.
// Returns a *NotSingularError when more than one Produto ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *ProdutoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{produto.Label}
	default:
		err = &NotSingularError{produto.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *ProdutoQuery) OnlyIDX(ctx context.Context) int {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Produtos.
func (pq *ProdutoQuery) All(ctx context.Context) ([]*Produto, error) {
	ctx = setContextOp(ctx, pq.ctx, "All")
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Produto, *ProdutoQuery]()
	return withInterceptors[[]*Produto](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *ProdutoQuery) AllX(ctx context.Context) []*Produto {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Produto IDs.
func (pq *ProdutoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, "IDs")
	if err = pq.Select(produto.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *ProdutoQuery) IDsX(ctx context.Context) []int {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *ProdutoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, "Count")
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*ProdutoQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *ProdutoQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *ProdutoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, "Exist")
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *ProdutoQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProdutoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *ProdutoQuery) Clone() *ProdutoQuery {
	if pq == nil {
		return nil
	}
	return &ProdutoQuery{
		config:     pq.config,
		ctx:        pq.ctx.Clone(),
		order:      append([]produto.OrderOption{}, pq.order...),
		inters:     append([]Interceptor{}, pq.inters...),
		predicates: append([]predicate.Produto{}, pq.predicates...),
		withOrdens: pq.withOrdens.Clone(),
		withItens:  pq.withItens.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithOrdens tells the query-builder to eager-load the nodes that are connected to
// the "ordens" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProdutoQuery) WithOrdens(opts ...func(*OrdemQuery)) *ProdutoQuery {
	query := (&OrdemClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withOrdens = query
	return pq
}

// WithItens tells the query-builder to eager-load the nodes that are connected to
// the "itens" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *ProdutoQuery) WithItens(opts ...func(*ItemOrdemQuery)) *ProdutoQuery {
	query := (&ItemOrdemClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withItens = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sku string `json:"sku,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Produto.Query().
//		GroupBy(produto.FieldSku).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *ProdutoQuery) GroupBy(field string, fields ...string) *ProdutoGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProdutoGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = produto.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Sku string `json:"sku,omitempty"`
//	}
//
//	client.Produto.Query().
//		Select(produto.FieldSku).
//		Scan(ctx, &v)
func (pq *ProdutoQuery) Select(fields ...string) *ProdutoSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &ProdutoSelect{ProdutoQuery: pq}
	sbuild.label = produto.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProdutoSelect configured with the given aggregations.
func (pq *ProdutoQuery) Aggregate(fns ...AggregateFunc) *ProdutoSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *ProdutoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !produto.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *ProdutoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Produto, error) {
	var (
		nodes       = []*Produto{}
		_spec       = pq.querySpec()
		loadedTypes = [2]bool{
			pq.withOrdens != nil,
			pq.withItens != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Produto).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Produto{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withOrdens; query != nil {
		if err := pq.loadOrdens(ctx, query, nodes,
			func(n *Produto) { n.Edges.Ordens = []*Ordem{} },
			func(n *Produto, e *Ordem) { n.Edges.Ordens = append(n.Edges.Ordens, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withItens; query != nil {
		if err := pq.loadItens(ctx, query, nodes,
			func(n *Produto) { n.Edges.Itens = []*ItemOrdem{} },
			func(n *Produto, e *ItemOrdem) { n.Edges.Itens = append(n.Edges.Itens, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *ProdutoQuery) loadOrdens(ctx context.Context, query *OrdemQuery, nodes []*Produto, init func(*Produto), assign func(*Produto, *Ordem)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Produto)
	nids := make(map[int]map[*Produto]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(produto.OrdensTable)
		s.Join(joinT).On(s.C(ordem.FieldID), joinT.C(produto.OrdensPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(produto.OrdensPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(produto.OrdensPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Produto]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Ordem](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "ordens" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (pq *ProdutoQuery) loadItens(ctx context.Context, query *ItemOrdemQuery, nodes []*Produto, init func(*Produto), assign func(*Produto, *ItemOrdem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Produto)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(itemordem.FieldProdutoID)
	}
	query.Where(predicate.ItemOrdem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(produto.ItensColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProdutoID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "produto_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (pq *ProdutoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *ProdutoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(produto.Table, produto.Columns, sqlgraph.NewFieldSpec(produto.FieldID, field.TypeInt))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, produto.FieldID)
		for i := range fields {
			if fields[i] != produto.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *ProdutoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(produto.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = produto.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProdutoGroupBy is the group-by builder for Produto entities.
type ProdutoGroupBy struct {
	selector
	build *ProdutoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *ProdutoGroupBy) Aggregate(fns ...AggregateFunc) *ProdutoGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *ProdutoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, "GroupBy")
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProdutoQuery, *ProdutoGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *ProdutoGroupBy) sqlScan(ctx context.Context, root *ProdutoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProdutoSelect is the builder for selecting fields of Produto entities.
type ProdutoSelect struct {
	*ProdutoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *ProdutoSelect) Aggregate(fns ...AggregateFunc) *ProdutoSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *ProdutoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, "Select")
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProdutoQuery, *ProdutoSelect](ctx, ps.ProdutoQuery, ps, ps.inters, v)
}

func (ps *ProdutoSelect) sqlScan(ctx context.Context, root *ProdutoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
