// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cliente is the predicate function for cliente builders.
type Cliente func(*sql.Selector)

// ItemOrdem is the predicate function for itemordem builders.
type ItemOrdem func(*sql.Selector)

// Ordem is the predicate function for ordem builders.
type Ordem func(*sql.Selector)

// Produto is the predicate function for produto builders.
type Produto func(*sql.Selector)
